name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:   # <-- erlaubt manuelles Starten

permissions:
  contents: read

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x   # immer neueste 2er-Version

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
